name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: 20
      - run: npm ci
      - run: npx eslint .

  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: 20
      - run: npm ci
      - run: npm pack
      - uses: actions/upload-artifact
        with:
          name: package
          path: '*.tgz'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action
        if: ${{ matrix.node-version == 20 }}

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: 20
      - run: npm ci
      - run: npx prettier --check .

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: 20
      - run: npm ci
      - run: npx tsc

  release:
    runs-on: ubuntu-latest
    needs:
      - eslint
      - test
      - pack
      - prettier
      - tsc
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-node
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - uses: actions/download-artifact
        with:
          name: package
      - run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
